

database:
    image: postgres
    hostname: vertx-database
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
       - "5432:5432"
    volumes:
        - ./sql/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    restart: always